apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pyton-app
  description: Python aoo displays time.
  annotations:
    github.com/project-slug: eduaran1/python-app
spec:
  type: serice
  lifecycle: experimental
  owner: development